PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDB_SALES CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDB_SALES-SALES_NO .
    FIELD ZDB_SALES-CUSTOMER_NAME .
    FIELD ZDB_SALES-HOLD .
    FIELD ZDB_SALES-ORDER_REASON .
    FIELD ZDB_SALES-ZDATE .
    FIELD ZDB_SALES-PRIORITY .
    FIELD ZDB_SALES-ORDER_TYPE .
    FIELD ZDB_SALES-ORDER_SOURCE .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDB_SALES-SALES_NO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
