PROCESS BEFORE OUTPUT.
 MODULE LISTE_INITIALISIEREN.
 LOOP AT EXTRACT WITH CONTROL
  TCTRL_ZDB_SALES_ITM CURSOR NEXTLINE.
   MODULE LISTE_SHOW_LISTE.
 ENDLOOP.
*
PROCESS AFTER INPUT.
 MODULE LISTE_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE LISTE_BEFORE_LOOP.
 LOOP AT EXTRACT.
   MODULE LISTE_INIT_WORKAREA.
   CHAIN.
    FIELD ZDB_SALES_ITM-SALES_ITM_NO .
    FIELD ZDB_SALES_ITM-SALES_NO .
    FIELD ZDB_SALES_ITM-MATERIAL_NO .
    FIELD ZDB_SALES_ITM-SUPPLIER_MATERIAL_NO .
    FIELD ZDB_SALES_ITM-PACKAGING .
    FIELD ZDB_SALES_ITM-TRANSPORT .
    MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
   ENDCHAIN.
   FIELD VIM_MARKED MODULE LISTE_MARK_CHECKBOX.
   CHAIN.
    FIELD ZDB_SALES_ITM-SALES_ITM_NO .
    FIELD ZDB_SALES_ITM-SALES_NO .
    MODULE LISTE_UPDATE_LISTE.
   ENDCHAIN.
 ENDLOOP.
 MODULE LISTE_AFTER_LOOP.
