PROCESS BEFORE OUTPUT.
 MODULE detail_init.
*
PROCESS AFTER INPUT.
 MODULE DETAIL_EXIT_COMMAND AT EXIT-COMMAND.
 MODULE DETAIL_SET_PFSTATUS.
 CHAIN.
    FIELD ZDB_SALES_ITM-SALES_ITM_NO .
    FIELD ZDB_SALES_ITM-SALES_NO .
    FIELD ZDB_SALES_ITM-MATERIAL_NO .
    FIELD ZDB_SALES_ITM-SUPPLIER_MATERIAL_NO .
    FIELD ZDB_SALES_ITM-DELIVERY_TIME .
    FIELD ZDB_SALES_ITM-PACKAGING .
    FIELD ZDB_SALES_ITM-TRANSPORT .
  MODULE SET_UPDATE_FLAG ON CHAIN-REQUEST.
 endchain.
 chain.
    FIELD ZDB_SALES_ITM-SALES_ITM_NO .
    FIELD ZDB_SALES_ITM-SALES_NO .
  module detail_pai.
 endchain.
