*&---------------------------------------------------------------------*
*& Report ZDRIVER_NIRMAL
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZDRIVER_NIRMAL.

TABLES: VBAK, VBAP, VBPA, ADRC, MAKT, MARC, PRCD_ELEMENTS.
DATA : GS_HEADER TYPE ZSTR_HEADER1,
       GT_ITEM   TYPE ZTT_SMARTFORM,
       GS_ITEM   TYPE ZSTR_ITEM2,
       LV_FM     TYPE RS38L_FNAM.


PARAMETERS P_VBELN TYPE VBAK-VBELN.

"VBAK Date
SELECT SINGLE
       VBELN,
       ERDAT,
       KNUMV
FROM VBAK
INTO @DATA(LS_VBAK)
WHERE VBELN = @P_VBELN.


GS_HEADER-DATE = LS_VBAK-ERDAT.
GS_HEADER-KNUMV = LS_VBAK-KNUMV.

"VBPA GET SOLD-TO-ADDRESS
SELECT SINGLE ADRNR
FROM VBPA
INTO @DATA(LV_ADRNR)
WHERE VBELN = @P_VBELN
AND PARVW = 'SP'.

"ADRC
SELECT SINGLE
     NAME1,
     STREET,
     STR_SUPPL1,
     STR_SUPPL2,
     STR_SUPPL3,
     COUNTRY,
     CITY1,
     REGION
FROM ADRC
INTO @DATA(LS_ADRC)
WHERE ADDRNUMBER = @LV_ADRNR.


GS_HEADER-NAME1     = LS_ADRC-NAME1.
GS_HEADER-STREET    = LS_ADRC-STREET.
GS_HEADER-CITY      = LS_ADRC-CITY1.
GS_HEADER-COUNTRY   = LS_ADRC-COUNTRY.
GS_HEADER-REGION    = LS_ADRC-REGION.

"ITEM DATA LOGIC
SELECT
    MATNR,
    KWMENG,
    UMVKZ
FROM VBAP
INTO TABLE @DATA(LT_VBAP)
WHERE VBELN = @P_VBELN.

"MOVE INTERNAL TABLE DATA TO WORK AREA
LOOP AT LT_VBAP INTO DATA(LS_VBAP).


  GS_ITEM-MATNR = LS_VBAP-MATNR.
  GS_ITEM-TOTAL_qty   = LS_VBAP-KWMENG.

"GET MATERIAL DESCRIPTION
  SELECT SINGLE MAKTX
  FROM MAKT
  INTO @DATA(LV_MAKTX)
  WHERE MATNR = @LS_VBAP-MATNR
  AND SPRAS = @SY-LANGU.


  GS_ITEM-MAKTX = LV_MAKTX.

"TOTAL PCS CALCULATION
  GS_ITEM-TOTAL_QTY = LS_VBAP-KWMENG * LS_VBAP-UMVKZ.

"HSN CODE MARC
  SELECT SINGLE STEUC
  FROM MARC
  INTO @DATA(LV_STEUC)
  WHERE MATNR = @LS_VBAP-MATNR.


  GS_ITEM-HSN = LV_STEUC.

"APPEND DATA
  APPEND GS_ITEM TO GT_ITEM.

  CLEAR GS_ITEM.

ENDLOOP.

"LOCATION (SHIP TO)
"VBPA
SELECT SINGLE ADRNR
FROM VBPA
INTO @DATA(LV_SHIPADR)
WHERE VBELN = @P_VBELN
AND PARVW = 'SH'.

"ADRC
SELECT SINGLE CITY1
FROM ADRC
INTO @DATA(LV_CITY)
WHERE ADDRNUMBER = @LV_SHIPADR.


*GS_HEADER-LOCATION = LV_CITY.

"PRICING LOGIC
SELECT SINGLE KWERT
FROM PRCD_ELEMENTS
INTO @DATA(LV_BASIC)
WHERE KNUMV = @GS_HEADER-KNUMV
AND KSCHL = 'ZASV'.


*GS_HEADER-BASIC_PRICE = LV_BASIC.

"GST CONDITIONS
SELECT SUM( KWERT )
FROM PRCD_ELEMENTS
INTO @DATA(LV_GST)
WHERE KNUMV = @GS_HEADER-KNUMV
AND KSCHL IN ('JOIG','JOSC','JOCG','JOUG').


*GS_HEADER-GST = LV_GST.

"TOTAL PRICE
*GS_HEADER-TOTAL_PRICE = GS_HEADER-BASIC_PRICE + GS_HEADER-GST.

"SMARTFORM FM CALL
CALL FUNCTION 'SSF_FUNCTION_MODULE_NAME'
  EXPORTING
    FORMNAME = 'ZSMART_SALES_QUOTATION'
  IMPORTING
    FM_NAME  = LV_FM.

CALL FUNCTION LV_FM
  EXPORTING
    IS_HEADER = GS_HEADER
  TABLES
    IT_ITEM   = GT_ITEM.
