*&---------------------------------------------------------------------*
*& Report ZSALES_REPORT
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSALES_REPORT_INTERACTIVE.

TABLES: VBAK, VBAP.
DATA: IT_VBAK TYPE TABLE OF ZSTR_VBAK,
      WA_VBAK TYPE ZSTR_VBAK.

DATA: IT_VBAP TYPE TABLE OF ZSTR_VBAP,
      WA_VBAP TYPE ZSTR_VBAP.

DATA: IT_FCAT  TYPE SLIS_T_FIELDCAT_ALV,
      WA_FCAT  TYPE SLIS_FIELDCAT_ALV,
      IT_FCAT1 TYPE SLIS_T_FIELDCAT_ALV,
      WA_FCAT1 TYPE SLIS_FIELDCAT_ALV.

DATA: IT_HEADER TYPE SLIS_T_LISTHEADER,
      WA_HEADER TYPE SLIS_LISTHEADER.


DATA: IT_HEADER1 TYPE SLIS_T_LISTHEADER,
      WA_HEADER1 TYPE SLIS_LISTHEADER.


SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_VBELN FOR VBAK-VBELN.
SELECTION-SCREEN: END OF BLOCK B1.

SELECT VBELN
         ERDAT
         ERZET
         ERNAM
         AUDAT
    FROM VBAK
    INTO TABLE IT_VBAK
    WHERE VBELN IN S_VBELN.

REFRESH IT_FCAT.

CLEAR WA_FCAT.
WA_FCAT-COL_POS   = 1.
WA_FCAT-FIELDNAME = 'VBELN'.
WA_FCAT-SELTEXT_L = 'Sales Order'.
APPEND WA_FCAT TO IT_FCAT.

CLEAR WA_FCAT.
WA_FCAT-COL_POS   = 2.
WA_FCAT-FIELDNAME = 'ERDAT'.
WA_FCAT-SELTEXT_L = 'Creation Date'.
APPEND WA_FCAT TO IT_FCAT.

CLEAR WA_FCAT.
WA_FCAT-COL_POS   = 3.
WA_FCAT-FIELDNAME = 'ERZET'.
WA_FCAT-SELTEXT_L = 'Entry Time'.
APPEND WA_FCAT TO IT_FCAT.

CLEAR WA_FCAT.
WA_FCAT-COL_POS   = 4.
WA_FCAT-FIELDNAME = 'ERNAM'.
WA_FCAT-SELTEXT_L = 'Created By'.
APPEND WA_FCAT TO IT_FCAT.

CLEAR WA_FCAT.
WA_FCAT-COL_POS   = 5.
WA_FCAT-FIELDNAME = 'AUDAT'.
WA_FCAT-SELTEXT_L = 'Document Date'.
APPEND WA_FCAT TO IT_FCAT.

CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
  EXPORTING
    I_CALLBACK_PROGRAM      = SY-REPID
    I_CALLBACK_USER_COMMAND = 'USER_COMMAND'
    IT_FIELDCAT             = IT_FCAT
    I_CALLBACK_TOP_OF_PAGE  = 'TOP_OF_PAGE'
  TABLES
    T_OUTTAB                = IT_VBAK
  EXCEPTIONS
    PROGRAM_ERROR           = 1
    OTHERS                  = 2.


FORM USER_COMMAND
     USING R_UCOMM LIKE SY-UCOMM
           RS_SELFIELD TYPE SLIS_SELFIELD.

  CASE R_UCOMM.

    WHEN '&IC1'.

      READ TABLE IT_VBAK INTO WA_VBAK
           INDEX RS_SELFIELD-TABINDEX.

      IF SY-SUBRC = 0.

        PERFORM DISPLAY_ITEMS USING WA_VBAK-VBELN.

      ENDIF.

  ENDCASE.

ENDFORM.

FORM DISPLAY_ITEMS USING P_VBELN TYPE VBAK-VBELN.

  REFRESH: IT_VBAP,
           IT_FCAT1.

  SELECT VBELN
         POSNR
         MATNR
         MATKL
         MEINS
    FROM VBAP
    INTO TABLE IT_VBAP
    WHERE VBELN = P_VBELN.

  CLEAR: WA_FCAT1.
  WA_FCAT1-COL_POS   = 1.
  WA_FCAT1-FIELDNAME = 'VBELN'.
  WA_FCAT1-SELTEXT_L = 'Sales Order'.
  APPEND WA_FCAT1 TO IT_FCAT1.
  CLEAR WA_FCAT1.


  WA_FCAT1-COL_POS   = 2.
  WA_FCAT1-FIELDNAME = 'POSNR'.
  WA_FCAT1-SELTEXT_L = 'Item No'.
  APPEND WA_FCAT1 TO IT_FCAT1.

  CLEAR WA_FCAT1.
  WA_FCAT1-COL_POS   = 3.
  WA_FCAT1-FIELDNAME = 'MATNR'.
  WA_FCAT1-SELTEXT_L = 'Material'.
  APPEND WA_FCAT1 TO IT_FCAT1.

  CLEAR WA_FCAT1.
  WA_FCAT1-COL_POS   = 4.
  WA_FCAT1-FIELDNAME = 'MATKL'.
  WA_FCAT1-SELTEXT_L = 'Material Group'.
  APPEND WA_FCAT1 TO IT_FCAT1.

  CLEAR WA_FCAT1.
  WA_FCAT1-COL_POS   = 5.
  WA_FCAT1-FIELDNAME = 'MEINS'.
  WA_FCAT1-SELTEXT_L = 'Base UOM'.
  APPEND WA_FCAT1 TO IT_FCAT1.


  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
      I_CALLBACK_PROGRAM = SY-REPID
      IT_FIELDCAT        = IT_FCAT1
      I_CALLBACK_TOP_OF_PAGE  = 'TOP_PAGE'
    TABLES
      T_OUTTAB           = IT_VBAP
    EXCEPTIONS
      PROGRAM_ERROR      = 1
      OTHERS             = 2.

ENDFORM.


DATA : LV_DATE TYPE STRING.
FORM TOP_OF_PAGE.

  CONCATENATE sy-datum+6(2)
              sy-datum+4(2)
              sy-datum+0(4)
           INTO lv_date
           SEPARATED BY '/'.

  WA_HEADER-TYP = 'H'.
  WA_HEADER-INFO = 'Sales Order'.
  APPEND WA_HEADER TO IT_HEADER.

  WA_HEADER-TYP = 'S'.
  WA_HEADER-KEY = 'Date'.
  WA_HEADER-INFO = LV_DATE.
  APPEND WA_HEADER TO IT_HEADER.
  CLEAR wa_header.

  wa_header-typ = 'S'.
  wa_header-key = 'PO Range'.
  wa_header-info = |{ S_VBELN-low } TO { S_VBELN-high }|.
  APPEND wa_header to it_header.
  CLEAR wa_header.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY = IT_HEADER
*     I_LOGO             =
*     I_END_OF_LIST_GRID =
*     I_ALV_FORM         =
    .

  refresh it_header.



ENDFORM.

FORM TOP_PAGE.
  WA_HEADER1-TYP = 'H'.
  WA_HEADER1-INFO = 'Sales Order Secondary List'.
  APPEND WA_HEADER1 TO IT_HEADER1.
  CLEAR: WA_HEADER1.

  CALL FUNCTION 'REUSE_ALV_COMMENTARY_WRITE'
    EXPORTING
      IT_LIST_COMMENTARY       = IT_HEADER1
*     I_LOGO                   =
*     I_END_OF_LIST_GRID       =
*     I_ALV_FORM               =
            .
  REFRESH IT_HEADER1.

  ENDFORM.
