*&---------------------------------------------------------------------*
*& Report ZSTD_MAT_PRD
*&---------------------------------------------------------------------*
*&
*&---------------------------------------------------------------------*
REPORT ZSTD_MAT_PRD1.

TABLES: MARA, MARC, MAKT, MAST, CRHD, AFPO, VBAP, PLAF.

TYPES: BEGIN OF STR_MARA,
         MATNR TYPE MARA-MATNR,
         MTART TYPE MARA-MTART,
         ERNAM TYPE MARA-ERNAM,
         LAEDA TYPE MARA-LAEDA,
*         MAKTG TYPE MARA-MAKTG,
       END OF STR_MARA.

TYPES: BEGIN OF STR_MARC,
         MATNR TYPE MARC-MATNR,
         WERKS TYPE MARC-WERKS,
       END OF STR_MARC.

TYPES: BEGIN OF STR_MAKT,
         MATNR TYPE MAKT-MATNR,
         MAKTX TYPE MAKT-MAKTX,
         MAKTG TYPE MAKT-MAKTG,
       END OF STR_MAKT.

TYPES: BEGIN OF STR_MAST,
         MATNR TYPE MAST-MATNR,
         WERKS TYPE MAST-WERKS,
       END OF STR_MAST.

TYPES: BEGIN OF STR_CRHD,
         WERKS TYPE CRHD-WERKS,
         ARBPL TYPE CRHD-ARBPL,
       END OF STR_CRHD.

*TYPES: BEGIN OF STR_MAPL,
*         MATNR TYPE MAPL-MATNR,
**         MTART TYPE MAPL-MTART,
*       END OF STR_MAPL.

TYPES: BEGIN OF STR_AFPO,
         MATNR TYPE AFPO-MATNR,
         AUFNR TYPE AFPO-AUFNR,
         VERID TYPE AFPO-VERID,
       END OF STR_AFPO.

TYPES: BEGIN OF STR_VBAP,
         MATNR TYPE VBAP-MATNR,
         NETWR TYPE VBAP-NETWR,
         VBELN TYPE VBap-VBELN,
       END OF STR_VBAP.

TYPES: BEGIN OF STR_PLAF,
         MATNR TYPE PLAF-MATNR,
         PLNUM TYPE PLAF-PLNUM,
       END OF STR_PLAF.

TYPES: BEGIN OF STR_FINAL,
         MATNR  TYPE MARA-MATNR,
         MTART  TYPE MARA-MTART,
         ERNAM  TYPE MARA-ERNAM,
         LAEDA  TYPE MARA-LAEDA,
         MAT1   TYPE MARC-MATNR,
         WERKS  TYPE MARC-WERKS,
         MAT2   TYPE MAKT-MATNR,
         MAKTX  TYPE MAKT-MAKTX,
         MAKTG  TYPE MAKT-MAKTG,
         MAT3   TYPE MAST-MATNR,
         WERKS1 TYPE MAST-WERKS,
         WERKS2 TYPE CRHD-WERKS,
         ARBPL  TYPE CRHD-ARBPL,
*         MAT4   TYPE MAPL-MATNR,
         MAT4   TYPE AFPO-MATNR,
         AUFNR  TYPE AFPO-AUFNR,
         VERID  TYPE AFPO-VERID,
         MAT5   TYPE VBAP-MATNR,
         NETWR  TYPE VBAP-NETWR,
         VBELN  TYPE VBAP-VBELN,
         MAT6   TYPE PLAF-MATNR,
         PLNUM  TYPE PLAF-PLNUM,
  color TYPE SLIS_T_SPECIALCOL_ALV,
       END OF STR_FINAL.

DATA: IT_MARA TYPE TABLE OF STR_MARA,
      WA_MARA TYPE STR_MARA.

DATA: IT_MARC TYPE TABLE OF STR_MARC,
      WA_MARC TYPE STR_MARC.

DATA: IT_MAKT TYPE TABLE OF STR_MAKT,
      WA_MAKT TYPE STR_MAKT.

DATA: IT_MAST TYPE TABLE OF STR_MAST,
      WA_MAST TYPE STR_MAST.

DATA: IT_CRHD TYPE TABLE OF STR_CRHD,
      WA_CRHD TYPE STR_CRHD.

*DATA: IT_MAPL TYPE TABLE OF STR_MAPL,
*      WA_MAPL TYPE STR_MAPL.

DATA: IT_AFPO TYPE TABLE OF STR_AFPO,
      WA_AFPO TYPE STR_AFPO.

DATA: IT_VBAP TYPE TABLE OF STR_VBAP,
      WA_VBAP TYPE STR_VBAP.

DATA: IT_PLAF TYPE TABLE OF STR_PLAF,
      WA_PLAF TYPE STR_PLAF.

DATA: IT_FINAL TYPE TABLE OF STR_FINAL,
      WA_FINAL TYPE STR_FINAL.

DATA: IT_FCAT TYPE SLIS_T_FIELDCAT_ALV,
      WA_FCAT TYPE SLIS_FIELDCAT_ALV.

DATA: it_sort TYPE SLIS_T_SORTINFO_ALV,
      wa_sort TYPE SLIS_SORTINFO_ALV.

DATA: wa_color TYPE slis_specialcol_alv.

DATA: wa_layout TYPE slis_layout_alv.


SELECTION-SCREEN: BEGIN OF BLOCK B1 WITH FRAME TITLE TEXT-001.
  SELECT-OPTIONS: S_MATNR FOR MARA-MATNR OBLIGATORY,
  S_WERKS FOR MARC-WERKS.
SELECTION-SCREEN: END OF BLOCK B1.

START-OF-SELECTION.

  SELECT
    MATNR
    MTART
    ERNAM
    LAEDA
    FROM MARA
    INTO TABLE IT_MARA
    WHERE MATNR IN S_MATNR.


  IF IT_MARA IS NOT INITIAL.

    SELECT
      MATNR
      WERKS
      FROM MARC
      INTO TABLE IT_MARC
      FOR ALL ENTRIES IN IT_MARA
      WHERE MATNR = IT_MARA-MATNR
      AND WERKS in s_werks.

    SELECT
      MATNR
      MAKTX
      MAKTG
      FROM MAKT
      INTO TABLE IT_MAKT
      FOR ALL ENTRIES IN IT_MARA
      WHERE MATNR = IT_MARA-MATNR.

    SELECT
      MATNR
      WERKS
      FROM MAST
      INTO TABLE IT_MAST
      FOR ALL ENTRIES IN IT_MARA
      WHERE MATNR = IT_MARA-MATNR.

    SELECT
      WERKS
      ARBPL
      FROM CRHD
      INTO TABLE IT_CRHD
      FOR ALL ENTRIES IN IT_MARC
      WHERE WERKS = IT_MARC-WERKS.

*    SELECT
*      MATNR
*      FROM MAPL
*      INTO TABLE IT_MAPL
*      FOR ALL ENTRIES IN IT_MARA
*      WHERE MATNR = IT_MARA-MATNR.

    SELECT
      MATNR
      AUFNR
      VERID
      FROM AFPO
      INTO TABLE IT_AFPO
      FOR ALL ENTRIES IN IT_MARA
      WHERE MATNR = IT_MARA-MATNR.

    SELECT
      MATNR
      NETWR
      VBELN
      FROM VBAP
      INTO TABLE IT_VBAP
      FOR ALL ENTRIES IN IT_MARA
      WHERE MATNR = IT_MARA-MATNR.

    SELECT
      MATNR
      PLNUM
      FROM PLAF
      INTO TABLE IT_PLAF
      FOR ALL ENTRIES IN IT_MARA
      WHERE MATNR = IT_MARA-MATNR.
  ENDIF.

*  SORT IT_MARA.
  LOOP AT IT_MARA INTO WA_MARA.

    CLEAR: WA_FINAL.
    DATA: LV_MATNR TYPE MARA-MATNR.
    LV_MATNR = WA_MARA-MATNR.

    CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
      EXPORTING
        INPUT  = LV_MATNR
      IMPORTING
        OUTPUT = WA_FINAL-MATNR.

*    WA_FINAL-MATNR = WA_MARA-MATNR.
    WA_FINAL-MTART = WA_MARA-MTART.
    WA_FINAL-ERNAM = WA_MARA-ERNAM.
    WA_FINAL-LAEDA = WA_MARA-LAEDA.


    READ TABLE IT_MARC INTO WA_MARC
     WITH KEY MATNR = WA_MARA-MATNR.
    IF SY-SUBRC = 0.
      WA_FINAL-MAT1    = WA_MARC-MATNR.
      WA_FINAL-WERKS  = WA_MARC-WERKS.
    ENDIF.

    IF S_WERKS[] IS NOT INITIAL.
      IF WA_MARC-WERKS NOT IN S_WERKS.
        CONTINUE.
      ENDIF.
    ENDIF.

    READ TABLE IT_MAKT INTO WA_MAKT
    WITH KEY MATNR = WA_MARA-MATNR.
    IF SY-SUBRC = 0.
      WA_FINAL-MAT2 = WA_MAKT-MATNR.
      WA_FINAL-MAKTX = WA_MAKT-MAKTX.
      WA_FINAL-MAKTG = WA_MAKT-MAKTG.
    ENDIF.

    READ TABLE IT_MAST INTO WA_MAST
    WITH KEY MATNR = WA_MARA-MATNR.
    IF SY-SUBRC = 0.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
        EXPORTING
          INPUT  = WA_MAST-MATNR
        IMPORTING
          OUTPUT = WA_FINAL-MAT3.

*      WA_FINAL-MAT3 = WA_MAST-MATNR.
      WA_FINAL-WERKS1 = WA_MAST-WERKS.
    ENDIF.

    READ TABLE IT_CRHD INTO WA_CRHD
    WITH KEY WERKS = WA_MARC-WERKS.
    IF SY-SUBRC = 0.
      WA_FINAL-WERKS = WA_CRHD-WERKS.
      WA_FINAL-ARBPL = WA_CRHD-ARBPL.
    ENDIF.

    READ TABLE IT_AFPO INTO WA_AFPO
    WITH KEY MATNR = WA_mara-MATNR.
    IF SY-SUBRC = 0.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
        EXPORTING
          INPUT  = WA_afpo-AUFNR
        IMPORTING
          OUTPUT = WA_FINAL-AUFNR.



      wa_Final-MAT4 = WA_AFPO-MATNR.
*      WA_FINAL-AUFNR = WA_AFPO-AUFNR.
      WA_FINAL-VERID = WA_AFPO-VERID.
    ENDIF.

    READ TABLE IT_VBAP INTO WA_VBAP
    WITH KEY MATNR = WA_Mara-MATNR.
    IF SY-SUBRC = 0.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
        EXPORTING
          INPUT  = WA_VBAP-VBELN
        IMPORTING
          OUTPUT = WA_FINAL-VBELN.


      WA_FINAL-MAT5 = WA_VBAP-MATNR.
      WA_FINAL-NETWR = WA_VBAP-NETWR.
*      WA_FINAL-VBELN = WA_VBAP-VBELN.
    ENDIF.

    READ TABLE IT_PLAF INTO WA_PLAF
    WITH KEY MATNR = WA_mara-MATNR.
    IF SY-SUBRC = 0.
      CALL FUNCTION 'CONVERSION_EXIT_ALPHA_OUTPUT'
        EXPORTING
          INPUT  = WA_PLAF-PLNUM
        IMPORTING
          OUTPUT = WA_FINAL-PLNUM.


      wa_Final-MAT6 = WA_PLAF-MATNR.
*      WA_FINAL-PLNUM = WA_PLAF-PLNUM.
    ENDIF.

*    WA_FINAL-MATNR = WA_MARA-MATNR.
*    SHIFT WA_FINAL-MATNR LEFT DELETING LEADING '0'.

    if wa_final-netwr > 189000000.

      CLEAR: wa_color.

      wa_color-fieldname = 'NETWR'.
      wa_color-color-col = 6. "Red
      wa_color-color-int = 1. "Intensified
      APPEND wa_color to wa_final-color.
      ENDIF.

    APPEND WA_FINAL TO IT_FINAL.

  ENDLOOP.

  PERFORM ADD_FIELDCATALOG USING 'MATNR' 'Material Number' '' .
  PERFORM ADD_FIELDCATALOG USING 'WERKS' 'Plant' ''.
  PERFORM ADD_FIELDCATALOG USING 'MTART' 'Materia Type' ''.
  PERFORM ADD_FIELDCATALOG USING 'MAKTX' 'Material Description' ''.
  PERFORM ADD_FIELDCATALOG USING 'MAT3' 'BOM Component' ''.
  PERFORM ADD_FIELDCATALOG USING 'ARBPL' 'Work Centre ' ''.
  PERFORM ADD_FIELDCATALOG USING 'VERID' 'Prod. version' ''.
  PERFORM ADD_FIELDCATALOG USING 'VBELN' 'Sales Order' ''.
  PERFORM ADD_FIELDCATALOG USING 'PLNUM' 'Planned Order ' ''.
  PERFORM ADD_FIELDCATALOG USING 'AUFNR' 'Prod. Order' ''.
  PERFORM ADD_FIELDCATALOG USING 'LAEDA' 'Last change.' ''.
  PERFORM ADD_FIELDCATALOG USING 'ERNAM' 'Created by.' ''.
  PERFORM ADD_FIELDCATALOG USING 'NETWR' 'Net Value' 'X'.

  CLEAR: wa_sort.
  wa_sort-spos = 1.
  wa_Sort-fieldname = 'MTART'.
  wa_sort-up = 'X'.
  wa_sort-subtot = 'X'.

  APPEND wa_Sort to it_sort.

  wa_layout-COLTAB_FIELDNAME = 'COLOR'.
SORT it_final by mtart.
  CALL FUNCTION 'REUSE_ALV_GRID_DISPLAY'
    EXPORTING
*     I_INTERFACE_CHECK  = ' '
*     I_BYPASSING_BUFFER = ' '
*     I_BUFFER_ACTIVE    = ' '
      I_CALLBACK_PROGRAM = SY-CPROG
*     I_CALLBACK_PF_STATUS_SET          = ' '
*     I_CALLBACK_USER_COMMAND           = ' '
*     I_CALLBACK_TOP_OF_PAGE            =
*     I_CALLBACK_HTML_TOP_OF_PAGE       = ' '
*     I_CALLBACK_HTML_END_OF_LIST       = ' '
*     I_STRUCTURE_NAME   =
*     I_BACKGROUND_ID    = ' '
*     I_GRID_TITLE       =
*     I_GRID_SETTINGS    =
      IS_LAYOUT          = wa_layout
      IT_FIELDCAT        = IT_FCAT
*     IT_EXCLUDING       =
*     IT_SPECIAL_GROUPS  =
      IT_SORT            = it_sort
*     IT_FILTER          =
*     IS_SEL_HIDE        =
*     I_DEFAULT          = 'X'
*     I_SAVE             = ' '
*     IS_VARIANT         =
*     IT_EVENTS          =
*     IT_EVENT_EXIT      =
*     IS_PRINT           =
*     IS_REPREP_ID       =
*     I_SCREEN_START_COLUMN             = 0
*     I_SCREEN_START_LINE               = 0
*     I_SCREEN_END_COLUMN               = 0
*     I_SCREEN_END_LINE  = 0
*     I_HTML_HEIGHT_TOP  = 0
*     I_HTML_HEIGHT_END  = 0
*     IT_ALV_GRAPHICS    =
*     IT_HYPERLINK       =
*     IT_ADD_FIELDCAT    =
*     IT_EXCEPT_QINFO    =
*     IR_SALV_FULLSCREEN_ADAPTER        =
*     O_PREVIOUS_SRAL_HANDLER           =
*     O_COMMON_HUB       =
* IMPORTING
*     E_EXIT_CAUSED_BY_CALLER           =
*     ES_EXIT_CAUSED_BY_USER            =
    TABLES
      T_OUTTAB           = IT_FINAL
* EXCEPTIONS
*     PROGRAM_ERROR      = 1
*     OTHERS             = 2
    .
  IF SY-SUBRC <> 0.
* Implement suitable error handling here
  ENDIF.


FORM ADD_FIELDCATALOG USING P_FIELD P_TEXT P_SUM.

  CLEAR: WA_FCAT.
  WA_FCAT-FIELDNAME = P_FIELD.
  WA_FCAT-SELTEXT_L = P_TEXT.
  WA_FCAT-DO_SUM    = P_SUM.

  APPEND WA_FCAT TO IT_FCAT.

ENDFORM.
